### ISSUE TITLE
deprecate "languageCode" custom field once the CTP cart & order have a locale

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#103]
Work on adding a locale to cart and order has started, so the current workaround custom field on the payment is not needed any more once that is published. 

backwards compatibility is an issue though - it must be checked whether the ZEG project uses the languageCode custom field. 

relates to  https://github.com/nkuehn/payment-integration-specifications/issues/4 

@butenkor  FYI. I haven't put this in a milestone yet.

**Comment by nkuehn** [comment]
See the comment in #57 for the reply from PAYONE on the question of the languages.

**Comment by andrii-kovalenko-ct** [comment]
so, after our conversation, basic workflow to define language in request we:
1) look in `payment.customfield.languageCode`
2) else: `[cart|order].customfield.languageCode`
3) else: leave it empty - payone will fallback to default one (probably "en")

we **should not** try to read this value from `payment.customer.locale.language`.

Is everything above correct?

**Comment by cneijenhuis** [comment]
I was not part of the conversation, but I think 2) should be `[cart|order].locale.language` ?

**Comment by andrii-kovalenko-ct** [comment]
ah, right: it has been added in commercetoolsSdkJvm 1.3.0 !

**Comment by nkuehn** [comment]
@andrii-kovalenko-ct  please don't forget to check whether the custom field on the payment exists at all.  No guarantee that it's in the type or the payment at all in the future.

**Comment by andrii-kovalenko-ct** [comment]
yeah: `java.util.Optional` is our checker ))
