### ISSUE TITLE
Evaluate effort of connecting multiple CTP projects in the same adapter instance (multitenant)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#110]
For hosting less instances of the adapter (for test vs. production, for marketplace setups, for multisite-clients) it would be necessary that the adapter can run multiple logical services of itself in one instance.  
I.e. it needs own configuration, an own CT SDK Client, own Notification listener URLs, own "handle" URLs etc. 
A more complex configuration file (or multiple) is OK, the current ENV-Var based setup would not scale. 

TODO here: check the existing implementation concept and do a rough estimation of the effort and  whether it triggers big refactoring or not. 

PS: it's okay if there is one "main" service / tenant with the existing configuration and URL convention and separately many others that are run from the multitenant setup

Related: #79  is similar but different.  It turned out that we rather need "the real deal" (i.e. this here) than the limited multi-portal approach.

**Comment by butenkor** [comment]
@nkuehn @andrii-kovalenko-ct I see that there was already task for that. I will just extend   requirements with points we discussed today:
- refactor service provider (main) to be able to fetch env var called "tenants" (example value: proj1, proj2, proj3) and create an instance of integration service per tenant. Each tenant instance should than load its credentials from env vars by tenant ID (prefix) and setup cron jobs and Spark endpoints (tenantID/existing URL)
- logger should be tenant specific (check for log widgets)
- evaluate memory consumption per tenant and define memory / cpu limits for docker container

**Comment by andrii-kovalenko-ct** [comment]
closed by #163, it has both multitenancy and multiportal support
