### ISSUE TITLE
Adapt job schedulers

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-payone-integration#113]
- Both jobs (`ScheduledJobShortTimeframe`, `ScheduledJobLongTimeframe`) should poll for messages of type: `PaymentCreatedMessage` and `PaymentTransactionAddedMessage`
- Schedule for `ScheduledJobShortTimeframe` and `ScheduledJobLongTimeframe` should be configurable over env variables. If not configured defaults are used.
- Scheduler defaults for `ScheduledJobShortTimeframe`: every minute
- Scheduler defaults for `ScheduledJobLongTimeframe`: run at startup and once a day (preferably nights - time zone issues...)

**Comment by nkuehn** [comment]
@butenkor short note of what we just analyze:

 * the "short" job is not necessary in the majority of usage patterns (they all trigger a synchronous handling in all use cases) and the adapter would be much more scalable if it would be off by default and would need to be activated as part of the tenant config (afaik it's already part of the config)
 * Know use cases for the "long" job are mostly related to service outages, could be considered to separate that or to reduce it to "on startup" to be on the safe side
 * if a "short" async handling is needed in a use case it should be done via message subscriptions, so in fact the "short" job could be removed altogether in favor of adding a message subscription consumer once a use case comes up. 

Overall that 
 a) could make the adapter much more scalable and hosting cheaper
 b) open the option to even make an OSS "Multi PSP" asdapter or to slim it down to be able to be run as a serverless function.

**Comment by butenkor** [comment]
I would vote to disable those jobs by default here as currently there is no real business use case and at some point move them to own repositories. One could still run them as service on demand. In the end they would subscribe/consume messages and trigger handle URL of current service.

**Comment by salander85** [comment]
The scheduled jobs no longer exists, therefore closing this issue.
