### ISSUE TITLE
Optionally Update the Order's Payment Status field

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#115]
To ease follow-up processing of the order and to reduce confusion about the meaning of the fields, the adapter could automatically update the payment status field on the Order (IF there is an order already). 

The Mapping should happen every time the service handles a payment, no matter if transactions actually change or not.

It means that a) if an order is there it needs to be always fetched.  b) if a payment is handled, the other payments of the order need to be fetched, too (e.g. via reference expansion when fetching the order). 

It maps between these two predefined state lists:
- http://dev.commercetools.com/http-api-projects-orders.html#paymentstate
- http://dev.commercetools.com/http-api-projects-payments.html#transactionstate

The payment status and state is ignored. The Mapping goes directly from Transactions to the Order as only these have finite states with predefined semantics. 

Proposed Logic (sketched with Roman but not finally reviewed): 
1. If an Order has no Transactions, the paymentState is left empty
2. If an Order has _only_ Pending Transactions, the paymentState is `Pending`
3. If an Order has _only_ Failed Transactions, the paymentState is `Failed`
4. If an Order has some Sucess(ful) Transactions across all associated Payments, the following math is applied:
   - Successful Authorization and CancelAuthorization Transactions are ignored
   - Successful Charge Transactions are added
   - Successful Refund and Chargeback Transactions are subtracted. 
   - If the result is higher than the gross cart total, the Order's paymentState is `CreditOwed`
   - If the result is lower than the gross cart total, the Order's paymentState is `BalanceDue`
   - If the result equals the gross cart total, the Order's paymentState is `Paid`  (hooray!)

Again, this logic is _off_ by default and would need to be enabled via a startup or config parameter.  In an eventual multi-tenant configuration it would need to be per tenant. 

@butenkor now in your hands, I'm off to vacation.  One thing you need to consider for your case is that Authorization does not trigger Paid, so the order would need to be exported to the ERP although the payment status on the Order is "pending".  Our Order Object's paymentState has no notion of Authorization, so that does not fit in. 

@cneijenhuis FYI - first payout of the semantically well-defined Transaction Types and Status.  Esp. that "Authorization" is strictly defined as "no money flow" helps here.

**Comment by andrii-kovalenko-ct** [comment]
https://github.com/commercetools/commercetools-payone-integration/issues/139
