### ISSUE TITLE
Document currently supported payment methods

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-payone-integration#118]
Would be great, if you could generate an overview, either in the Readme or an additional file, which of the PAYONE payment methods are support with the current version of the integration.

Thanks!

**Comment by floriansattler** [comment]
@mmoelli currently following methods are supported.
- Credit card
- Paypal
- Cash in advance
- Postfinance

We will update documentation accordingly.

**Comment by ahalberkamp** [comment]
Allready done
