### ISSUE TITLE
Implement travis build to create conventional "latest" and "production" tags

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#124]
Now any master push creates "latest", never "production" tag. From the description from Sven:

> actually we have a quite a "standard" way for the deployment: use autodeployment + tag "latest" in staging and "autodeploy" + tag "production" (or dedicated tag) in production

**Comment by butenkor** [comment]
https://github.com/commercetools/commercetools-payment-to-order-processor#docker-image-tags-table

**Comment by andrii-kovalenko-ct** [comment]
fixed: 6deea0ef969abfcbbc141b0bab568db2a165d32b

**Comment by salander85** [comment]
This was already fixed. Therefore closing this ticket.
