### ISSUE TITLE
Add "x-correlation-id" to error logs

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#132]
In case of errors from CTP platform - add `x-correlation-id` response header value to the logs - this is important for future customer reports and support.

**Comment by andrii-kovalenko-ct** [comment]
it is included by default

**Comment by heshamMassoud** [comment]
I think it would make sense here to log a correlation id for any coming request to the service. The correlation id can be either taken from the request header coming from a downstream service or if not in the header, the service should generate one and add it to the header of any requests it issues to any upstream service (e.g. commercetools, payone, etc..).

**Comment by ahalberkamp** [comment]
Already implemented
