### ISSUE TITLE
Remove slow logging details

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#133]
In current `log4j.properties` we use the next pattern:
```
log4j.appender.STDOUT.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n
```
In the same time from the [log4j doc](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html) (considering `%F:%L` properties (file name and line number):

> WARNING Generating caller location information is extremely slow and should be avoided unless execution speed is not an issue.

Think we have to omit this properties and output only stack-trace in case of exceptions.

 - [x] [remove direct referenced to log4j, use _slf4j_ facade interfaces only](https://github.com/commercetools/commercetools-payone-integration/issues/128) (#128)
 - [x] switch to _logback_ instead of _log4j_ and reuse configs from other _Play_ based shops 
 - [ ] apply JSON appender to log stack traces as one event
 - [x] [Add "x-correlation-id" to error logs](https://github.com/commercetools/commercetools-payone-integration/issues/132) (#132)

**Comment by andrii-kovalenko-ct** [comment]
@butenkor what do you think?

**Comment by butenkor** [comment]
I would switch to logback instead as it is successor of log4j and it might not suffer from issues listed here.

**Comment by andrii-kovalenko-ct** [comment]
PR created: https://github.com/commercetools/commercetools-payone-integration/pull/144

**Comment by andrii-kovalenko-ct** [comment]
done in https://github.com/commercetools/commercetools-payone-integration/pull/144
JSON logging moved to separate issue https://github.com/commercetools/commercetools-payone-integration/pull/144
