### ISSUE TITLE
Change last transaction/paymentStatus when request to P1 failed 

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#137]
@butenkor @ahalberkamp @lojzatran 

One interesting case i found today in the tests:
look for payment [_3a0f758f-ce67-4c05-a4c8-3f30f0cc4f24_ in `payone-integration-tests-heroku-17` project](https://impex.commercetools.com/playground?endpoint=payments&method=read&payload=&file-payload=&resourceUpdateId=&resourceId=&expand=&query-id-staged=staged&query-where=id%3D"3a0f758f-ce67-4c05-a4c8-3f30f0cc4f24"&query-sort=&query-sort-order=asc&query-page=&query-perPage=&query-expand=&query-staged=staged&search-lang=&search-text=&search-facet=&search-filter=&search-filter-query=&search-filter-facets=&search-sort=&search-sort-order=asc&search-page=&search-perPage=&search-expand=&search-staged=staged&suggest-lang=&suggest-searchKeywords=&suggest-limit=&suggest-staged=staged&resourceVersion=)

It has the last transaction _Pending_, which is correct, but the last interface interaction failed:

> "response": "{\"status\":\"ERROR\",\"errorcode\":\"-1000001\",\"errormessage\":\"Integration Service Exception: Payone POST request failed. Cause: org.apache.http.NoHttpResponseException: api.pay1.de:443 failed to respond\",\"customermessage\":\"Error on payment transaction processing.\"}"

This is an error message which is generate by _payone-integration-service_ itself when `payonePostService.executePost(request)` is interrupted by exception. This means the request `request=authorization` to Payone has not been processed at all. See [TransactionBaseExecutor#exceptionToResponseJsonString](https://github.com/commercetools/commercetools-payone-integration/blob/6b051ff774fa6b29506bec65982c5a6179284d0c/service/src/main/java/com/commercetools/pspadapter/payone/transaction/TransactionBaseExecutor.java#L86-L86) for more details.

In the same time the _payment.transaction[0].state_ remains _Pending_ and _paymentStatus_ remains empty, this the payment looks still valid.

What should we do in this case with payment/transaction state/status? From shallow view i see 2 points:

  - update the associated transaction state to `Failure`
  - update the _paymentStatus_ with the error messages
  - (do both?)

**Comment by ahalberkamp** [comment]
I think the error from above is a temporary error, so in this case the request should be send again by using a "retry" process.

**Comment by butenkor** [comment]
Some ideas:
- Check if http client timeouts for both connection to server as also read response are properly set. Setting it to 3 - 5 seconds seems worth a try.
- Another possibility might be that Herokus's integration service is not used to often so pooled connections get stale and might throw above exception (https://github.com/google/google-api-java-client/issues/1060). In this case we could use custom "keep alive" strategy: http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d5e425
- Use newest version 4.5.6 as current one is 4.5.5
- Use retry mechanism as described [here](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html#d5e316) but beware that retry for POST requests are not really recommended.

**Comment by CT-thorstenbayer** [comment]
we are already handling the filed statusses in our commercetools payment object
