### ISSUE TITLE
Allow logging events as JSON

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-payone-integration#148]
Currently multiline logs are not treated as single log event, which makes log analysis harder (logstash, logentries). Consider usage of [log4j 2](https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout) or logback [logstash-logback-encoder](https://github.com/logstash/logstash-logback-encoder/tree/logstash-logback-encoder-4.9)

Related: https://github.com/commercetools/commercetools-payone-integration/issues/133

**Comment by ahalberkamp** [comment]
The JSON-format is already configured for logback
