### ISSUE TITLE
Run integration tests when the application is completely initialized on Heroku

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#149]
Sometimes the integration/functional tests started before the app is actually available on Heroku (the app is successfully deployed and started, but the HTTP service is not initialized yet).

For now we use Jerry-rig solution in `.travis.yml` - make 10 seconds timeout between application deploy and the tests run:
```
after_deploy:
- sleep 10s # wait 10 seconds to run the deployed service completely before starting functional tests
```

Instead of the it is better to wait while the service is completely initialized, some possible approaches:

  - implement a script which periodically checks `/health` URL till it is successfully responsed
  - look for some standard Heroku solutions
  - other ideas???

**Comment by ahalberkamp** [comment]
As we don`t use heroku anymore, this issue can be closed
