### ISSUE TITLE
Fix selenium test for new Sofortüberweisung web design

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#151]
Sofortüberweisung site changed design, now the tests fail.

**Comment by andrii-kovalenko-ct** [comment]
fixed https://github.com/commercetools/commercetools-payone-integration/pull/152

**Comment by andrii-kovalenko-ct** [comment]
Needs changes again

**Comment by ahalberkamp** [comment]
As we don`t have selenium test anymore, this can issue  be closed
