### ISSUE TITLE
Avoid application mandatory properties verification in gradle application run plugin   

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#153]
in `build.gradle` re-factor `#assertAndGetServiceProperties()` function to avoid assertion - this should be done by the app only, the build script should just map all available properties from the list ignoring missing ones

**Comment by JudeNiroshan** [comment]
in `build.gradle` method `#assertAndGetServiceProperties()` is no longer available. Therefore closing this ticket.
