### ISSUE TITLE
Add salutation and title fields to payone request

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#156]
Some of invoice payment methods in Payone could print customer info on the pay bill, thus it is nice to map `salutation` and/or `title` to the Payone requests, so they can print it correctly on the documents.

**Comment by JudeNiroshan** [comment]
We are using the `title`. https://github.com/commercetools/commercetools-payone-integration/blob/7a7563a321b426eb8cd335f49703400d68f70f05/service/src/main/java/com/commercetools/pspadapter/payone/mapping/MappingUtil.java#L70

Therefore, this ticket can be closed.
