### ISSUE TITLE
Simplify PayonePostService#executePost(BaseRequest)

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#165]
according to the discussion https://github.com/commercetools/commercetools-payone-integration/pull/159#discussion_r126475837

`PayonePostService#executePost(BaseRequest)` should accept _simple-and-stupid_ String-String map, instead of complex request, and all complex mapping from the Request object to the Map should be done by separate extendable converter.

**Comment by JudeNiroshan** [comment]
We are closing this as the ROI of this change is quite low. We have to some considerable amount of places which looks quite clear passing the BaseRequest as the parameter. Therefore, no real benefit to changing the method signature.
