### ISSUE TITLE
Provide swagger specification of public endpoints

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-payone-integration#169]
Pros:
- generated SDK
- generated UI for API discovery
- API consistency 
- generated API documentation

Party started [here](https://github.com/nkuehn/payment-integration-specifications)

**Comment by JudeNiroshan** [comment]
@butenkor Do you think this is necessary at this moment? Given the fact that customers of this library haven't requested this specification.

**Comment by JudeNiroshan** [comment]
It seems outdated as of now. Therefore closing this issue.
