### ISSUE TITLE
Avoid MD5

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#177]
No comments - just use `SHA-2` everywhere.

Note: payone supports property `Configuration -> Payment Portals -> Extended -> Method hash calculation`= **`md5 oder sha2-384 (during migration)`**. Use it everywhere where it is possible so far, and later switch to explicitly  **`sha2-384`**.

Linked issue: #87

**Comment by andrii-kovalenko-ct** [comment]
@LEQADA 
Talked to Payone support:
_sha2_ is implemented only for client API. Server API (which we use) remains completely on _md5_ and there is no any plans to change this soon ;(

So, pls, revert the changes and put `@SuppressWarnings("deprecation")` with respective comment on those calls.

**Comment by LEQADA** [comment]
Fixed by https://github.com/commercetools/commercetools-payone-integration/pull/178
