### ISSUE TITLE
Create dedicated REFUND/CHARGEBACK transaction in CTP when "debit" notification recieved

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#195]
1. **Clarify "txaction=debit" notification means "refund" or verify with Payone support how to recognize refund notification**

2. Implement new `DebitNotificationProcessor` (`RefundXX/ChargebackXX`) processor which adds new transaction (`REFUND` or `CHARGEBACK` ?) with status _Success_ (or _Pending_ ?) to the payment.

**Comment by JudeNiroshan** [comment]
Please explain the following terms and workflows:
1. What is meant by `"DEBIT"`?
2 We already have refund workflow implemented. What is missing in that workflow?
3. What is `"CHARGEBACK"` is meant for?

**Comment by JudeNiroshan** [comment]
At the moment no customer has requested this feature. Therefore closing the issue.
