### ISSUE TITLE
Remove scheduled jobs

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-payone-integration#210]
- [x] Remove scheduled jobs from the service
  - [ ] Investigate how to replace such a functionality by [CTP API Extensions](https://deploy-preview-824--commercetools-documentation.netlify.com/tutorial-extensions.html)

related issue: #113

**Comment by andrii-kovalenko-ct** [comment]
@butenkor @nkuehn 
I'm thinking to remove this functionality from the service. As we discussed with Roman - neither of known customers used this functionality, although it creates some problems, for example, `ConcurrentModificationException`, when payment is handled by scheduled job before actual handling by customer, and the customer receives the exception.

I could start this change this week

**Comment by nkuehn** [comment]
I think It would make sense to directly move the whole integration pattern over to API extensions and remove the explicit "handle" call from the checkout completely.   That would remove a whole class of problems even beyond the one described here. 

I just don't know how to migrate under load - the connector would need to correctly "handle" the the "handle" calls in a transitional period when the API extension has also already triggered the payment.

**Comment by JudeNiroshan** [comment]
@butenkor At this moment, we have completely removed all the quartz cronjobs in this library.

Do we really need to implement the delayed response handling through API Extensions? Do you see any business value at this moment? If not can we close this ticket?

**Comment by JudeNiroshan** [comment]
Migration to API Extension would require major refactoring & wouldn't be in the scope of the current project.
