### ISSUE TITLE
replace unirest by fluent-hc, generally check dependency bloat. 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#35]
(technical debt)

Due to lack of experience with microservices there was some back and forth concerning framework and library use in the very first days of the implementation of the service. 

This led to a bunch of HTTP / REST frameworks being pulled in and weird choices like a full REST server framework just to do a simple HTTP call. 

currently there is the HTTP client from the CTP SDK, unirest and fluent-hc being used for doing external HTTP calls and maybe even more other "overkill dependencies".  This makes it harder for a developer to work with the codebase than necessary and creates work keeping the dependencies up to date to stay secure (HTTP libs should always be on a current enough patch level, esp. those providing a server). 

(enough description now?   )

**Comment by butenkor** [comment]
@andrii-kovalenko-ct Just curious - why did you close it without any comment?

**Comment by andrii-kovalenko-ct** [comment]
because it doesn't have any description ))

**Comment by andrii-kovalenko-ct** [comment]
resolved by https://github.com/commercetools/commercetools-payone-integration/pull/193
