### ISSUE TITLE
Check Licenses of Libraries whether "fat jar" distribution is okay. 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#36]
Background:  This is only relevant if the resulting fat jar is supposed to be published into maven central or other public repositories.

**Comment by andrii-kovalenko-ct** [comment]
- we don't distribute a library - we distribute a service (docker image).
- we don't modify any included third-party libraries.

**Comment by nkuehn** [comment]
@andrii-kovalenko-ct  your arguments are legally not correct but let's not get into the discussion too deep. 

TL;DR concerning the current state: 

 * we're should not publish fatjar build on mavencentral or other public repositories like public docker repositories (no matter whether in a docker container or as a jar or whatever - licenses give a shit how many layers of gift wrap paper you wrap around it. 
 * we can do whatever we want with the builds in our own repositories. 
 * we can leave the repo open as is

**Comment by andrii-kovalenko-ct** [comment]
ok, reopen it

**Comment by nkuehn** [comment]
since this repo is open I pulled it into versioneye and did a quick check - the direct dependencies are all liberal and therefore okay ( MIT / Apache / BSD ) in my opinion. 

There are some LGPLed ones in the transitive dependencies but I couldn't check yet which result from test dependencies and which not (there's "fat" stuff like selenium in the test dependencies. 

I guess we're okay and will close this now. 

Old learning:  adding too many and too fat dependencies (fat in both their own scope and the amount of transitive dependencies they use) causes all kinds of follow-up headaches. Stay slim from the beginning.

**Comment by andrii-kovalenko-ct** [comment]
thx, @nkuehn
