### ISSUE TITLE
Remaining Online Transfer methods

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#37]
[ ] eps
[ ] giropay
[ x ] Ideal

**Comment by leungkinghin** [comment]
Ideal payment has been implemented. Have to check whether EPS and Giropay is necessary to be added now.

**Comment by leungkinghin** [comment]
Discussed with the team. We don't have necessity to add new payment methods at this moment.

**Comment by ahalberkamp** [comment]
Eps and giropay are allready integrated
