### ISSUE TITLE
Credit Card: AuthorizationTransactionExecutor handles PAYONE-request failure incorrectly

### ISSUE THREAD

**Issue by sesamzoo** [commercetools/commercetools-payone-integration#44]
# Problem

In case of an exception during the request sent to PAYONE, an [interface interaction of type response is added to the payment](https://github.com/commercetools/commercetools-payone-integration/blob/e7e105e2c55c241185e568ea0ad0bf9ee60512a4/service/src/main/java/com/commercetools/pspadapter/payone/transaction/creditcard/AuthorizationTransactionExecutor.java#L152).
This means that the request required to trigger the transaction won't be sent again, hence the payment will stay in state Pending forever.
# Solution

Add an `PAYONE_INTERACTION_TEMPORARY_ERROR` instead.
## Needs Clarification

Which status should be returned if this transaction is processed via a request to the HTTP endpoint `handle/{resource-type}/{id}`.

**Comment by lojzatran** [comment]
This issue has been resolved here: https://github.com/commercetools/commercetools-payone-integration/pull/202/files#diff-8d537cb313d4b6193617c7a03baa6ae4fd4e115527ea0a97e3f24612231f7ab2R167.
In case of error the payment will have a transaction with status FAILURE.
