### ISSUE TITLE
(implement authentication) Support response 403 (Forbidden) in HTTP endpoint handling

### ISSUE THREAD

**Issue by sesamzoo** [commercetools/commercetools-payone-integration#45]
Find API specification [here](https://github.com/nkuehn/payment-integration-specifications) or view [in Swagger editor](http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/nkuehn/payment-integration-specifications/master/Payment-Integration-Api.swagger.yml).

Related to issue #9.

**Comment by butenkor** [comment]
@andrii-kovalenko-ct I think there was no final conclusion on authentication yet as payment as also cloud providers (lambda, functions) are not supporting all of them.

**Comment by andrii-kovalenko-ct** [comment]
agree.
One of the possible solutions:
use secure unique long string as a part of the all exposed URLs, for instance:

`https://host.com/`**`27v5doSEuE9pEcMxNZzxDfxUVBQxuF0QQjFkOBxIk`**`/payone/notifications`
`https://host.com/`**`27v5doSEuE9pEcMxNZzxDfxUVBQxuF0QQjFkOBxIk`**`/payone/notifications`

where **`27v5d...kOBxIk`** - some unique secret property, set in the docker container settings (e.g. environment variables)

**Comment by butenkor** [comment]
Meanwhile if required this can be handled by many hosting providers on the gateway level. In general having this URL public does not pose any security risk.
