### ISSUE TITLE
Store status in paymentStatus.interfaceCode and paymentStatus.interfaceText

### ISSUE THREAD

**Issue by sesamzoo** [commercetools/commercetools-payone-integration#55]
See the [field mapping specification](https://github.com/commercetools/commercetools-payone-integration/blob/master/docs/Field-Mapping.md#commercetools-payment-resource-mapping) for details.

**Comment by JudeNiroshan** [comment]
We can close this issue as we have already implemented the mapping here -> https://github.com/commercetools/commercetools-payone-integration/blob/ed35e69adeb51a09e5fdd099c0ce2e8ceadb73b7/service/src/main/java/com/commercetools/pspadapter/payone/notification/NotificationProcessorBase.java#L194
