### ISSUE TITLE
rename service jar to a self-explanatory name 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#69]
The service fat jar is currently named  `service-0.1-SNAPSHOT.jar`. 

As it's distributed and used on servers outside the context of the source code it should get a more self-explanatory name that communicates "commercetools" / "CT", "payone" / "p1" and "integration" and "service" in some conventional way.

**Comment by andrii-kovalenko-ct** [comment]
now it is `commercetools-payone-integration.jar`, not so important though since it is packed to docker image
