### ISSUE TITLE
Algorithm to identify CT transactions that need to be executed must not stop recursion just because a transaction's state is still Pending after its execution

### ISSUE THREAD

**Issue by sesamzoo** [commercetools/commercetools-payone-integration#73]
# Problem

The current algorithm - _"handle oldest transaction with state Pending"_ - is not sufficient for scenarios like _4.2.7 Sample: preauthorization/capture, REC with credit note_ in PAYONE's Server API documentation:
The **Charge** transaction of the invoice is still _Pending_ (buyer hasn't paid anything, yet) while a **Refund** transaction (credit note issued by merchant) is requested (and completed).

Another scenario is described in #42.
# Solution

To be defined...
# See also
#9's discussion

**Comment by ahalberkamp** [comment]
This will be fixed in this issue #208
