### ISSUE TITLE
Add Multi-Portal Capability

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#79]
The current implementation is focused on supporting the typical case of one payone production portal ID. 

For larger implementations it is required to enable multi-portal setups, e.g. mapping the "distributionChannel" attribute of the Cart that relates to the payment to a portal ID or by other, more PAYONE-specific modeling in the CTP. 

(multi-CTP-project / multi-PO-merchant setups are a requirement, too but should be tracked in separate issues as they are a bigger change due to real multitenancy concerning API clients, message listeners etc.)

**Comment by andrii-kovalenko-ct** [comment]
duplicated in #110 and #154
