### ISSUE TITLE
Migrate interface interaction data format to standard JSON

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-payone-integration#82]
the "response" and "notification" fields are filled with a custom serialization which has two problems:
- it is not defined and cannot be realiably read by 3rd parties
- it does only contain PO response values that are mapped in the java implementation, but should contain all fields, i.e. the raw data from PAYONE

**Comment by salander85** [comment]
Was already implemented by https://github.com/commercetools/commercetools-payone-integration/pull/120
