### ISSUE TITLE
How to handle hash values?

### ISSUE THREAD

**Issue by sesamzoo** [commercetools/commercetools-payone-integration#87]
# Problem

At the moment the environment variable `PAYONE_KEY` contains the raw value and its md5 hash value is calculated by the integration service.
If PAYONE starts to support sha2-384 hash values the integration service will have to be modified.
# Proposed Solution

Provide the hash value in the environment variable `PAYONE_KEY` (and modify the integration service accordingly) so that the integration service does not have to care about the hash function at all.
# Alternative Solution

Use another setting to specify the hash function to be used.

**Comment by salander85** [comment]
Closing the issue, as deprecation of MD5 not announced by payone yet.
https://github.com/commercetools/commercetools-payone-integration/issues/177#issuecomment-341411154
