### ISSUE TITLE
Payone no response leads to missing redirectUrl

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-payone-integration#92]
In contrast to different statements from Payone, it is in fact possible that the API may not respond (in time). A functional test proved that, see payment b9a45303-0f5e-4f46-b216-afe20846b73a in Heroku project:

`"response": "Payone POST request failed. Cause: org.apache.http.NoHttpResponseException: api.pay1.de:443 failed to respond"`

The result is a missing redirectUrl field in the payment which is needed for the shop to resume the checkout process.

**Comment by salander85** [comment]
There's a retry logic to avoid those cases. If this happens the shop needs to receive an exception from this library. This is current behaviour, which is correct.
